sequenceDiagram
    participant Client
    participant RoomMgtSrv
    participant NotifSrv
    participant CharMgtSrv

    Client ->>+ RoomMgtSrv: Create Room
    RoomMgtSrv ->>+ CharMgtSrv: Initialize Room Characters
    CharMgtSrv -->>- RoomMgtSrv: Characters Initialized
    RoomMgtSrv -->>- Client: Room Created

    Client ->> NotifSrv: Subscribe to Room Notifications
    NotifSrv -->> Client: Subscription Confirmed

    Client ->>+ CharMgtSrv: Get Room Characters
    CharMgtSrv -->>- Client: Room Characters
