version = 0.1

[default]
[default.global.parameters]
stack_name = "munch-helper-user-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

[default.build.parameters]
template_file = "sam/template.yaml"

[default.local_start_api.parameters]
template_file = "sam/template.yaml"

[default.local_invoke.parameters]
template_file = "sam/template.yaml"

[default.deploy.parameters]
template_file = "sam/template.yaml"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "UserMongoUri=mongodb://host.docker.internal:27021/munch_user_service"