version = 0.1

[default]
[default.global.parameters]
stack_name = "munch-helper-user-service"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[default.build.parameters]
template_file = "sam/template.yaml"

[default.local_start_api.parameters]
template_file = "sam/template.yaml"

[default.local_invoke.parameters]
template_file = "sam/template.yaml"

[default.deploy.parameters]
template_file = ".aws-sam/build/template.yaml"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "UserMongoUri=mongodb+srv://sandbox.4ty9upc.mongodb.net/user?authSource=%24external&authMechanism=MONGODB-AWS&appName=Sandbox RoomMongoUri=mongodb+srv://sandbox.4ty9upc.mongodb.net/room?authSource=%24external&authMechanism=MONGODB-AWS&appName=Sandbox CharacterMongoUri=mongodb+srv://sandbox.4ty9upc.mongodb.net/character?authSource=%24external&authMechanism=MONGODB-AWS&appName=Sandbox CharacterServiceUrl=https://helpamunch.click/api CharacterCallTimeoutMs=2000 RoutePrefix=/api/"