default_platform(:ios)

platform :ios do
    desc "Push a new beta build to TestFlight"
    lane :beta do
        # Retrieve the api key from key file
        # api_key = app_store_connect_api_key(
        #     # Replace key_id and issuer_id with your api key key and issuer IDs
        #     key_id: "[key_id]",
        #     issuer_id: "[issuer_id]",
        #     key_filepath: "AppStoreConnectApiKey.p8",
        #     duration: 1000,
        #     in_house: false
        # )

        # Retrieve signing certificate from file
        # import_certificate(
        #     certificate_path: "PrivateKey.p12",
        #     keychain_name: ENV["MATCH_KEYCHAIN_NAME"]
        # )

        # Import mobile provisioning profile from app store
        # get_provisioning_profile(
        #     filename: "distribution.mobileprovision",
        #     # Replace provisioning_name with your provisioning profile name
        #     provisioning_name: "[provisioning_name]",
        #     ignore_profiles_with_different_name: true,
        #     readonly: true,
        #     api_key: api_key
        # )

        # Get latest build number
        # previous_build_number = latest_testflight_build_number(
        #     api_key: api_key
        # )

        # Increment build number
        # increment_build_number(
        #     # Replace xcodeproj
        #     xcodeproj: "munchhelper.xcodeproj",
        #     build_number: previous_build_number + 1
        # )

        # Disable automatic code signing, so the signing certificate on the filesystem can be used
        # update_code_signing_settings(
        #     use_automatic_signing: false,
        #     # Replace xcodeproj, bundle_identifier and profile_name
        #     path: "munchhelper.xcodeproj",
        #     bundle_identifier: "click.helpamunch.mobileapp",
        #     profile_name: "munchhelper",
        # )

        # Build the iOS app
        build_app(
            workspace: "munchhelper.xcworkspace",
            scheme: "munchhelper",
            configuration: "Release",
            export_method: "app-store",
            export_options: {
                signingStyle: "automatic"
            },
            xcargs: "-allowProvisioningUpdates"
        )

        # Upload app to TestFlight, skipping waiting for build processing to reduce CI credit waste
        # upload_to_testflight(
        #     skip_waiting_for_build_processing: true,
        #     api_key: api_key
        # )
    end
end
