default_platform(:android)
app_slug = "munch-helper"

gradle_properties = {}
if ENV["ANDROID_SIGNING_KEY_PASSWORD"]
  gradle_properties = {
    "android.injected.signing.store.file" => ENV["ANDROID_SIGNING_KEY_PATH"],
    "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"],
    "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_KEY_ALIAS"] || "upload-key-alias",
    "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"]
  }
else
  UI.error("Android signing key password not found in environment variables. Please set ANDROID_SIGNING_KEY_PASSWORD to the password of your signing key.")
end

platform :android do
    desc "Build only a release version of the app"
    lane :build do
        # Grab the latest build number from the Play Store
        previous_build_number = google_play_track_version_codes(
            track: "internal"
        )[0]

        # Increment the build number
        increment_version_code(
            gradle_file_path: "app/build.gradle",
            version_code: previous_build_number + 1
        )
        gradle(
            gradle_path: "./gradlew",
            task: "assembleRelease bundleRelease",
            print_command: false,
            properties: gradle_properties
        )
    end
    desc "Upload the signed release build to the Play Store internal track"
    lane :deploy do
        upload_to_play_store(
            track: "internal",
            skip_upload_apk: true,
            release_status: "draft"
        )
    end
    desc "Build and deploy a new version to the Google Play internal track"
    lane :beta do
        build()
        deploy()
    end
end